### PR TITLE
GA events

### PR DESCRIPTION
**Pull request by seromenho**

### CODE REVIEW

**Review by Joao-pina-fernandes — APPROVED** [review]

**Comment by Joao-pina-fernandes** [comment]
tests missing

**Comment by seromenho** [comment]
@Joao-pina-fernandes wanna test it?

**Comment by seromenho** [comment]
Btw it's not only this one.
It's all of this: [GA Events](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Aseromenho+GA+events)

**Comment by seromenho** [comment]
Closing this has `Fliplet.Navigate.to` will track link events.

**Pull request closed without merging**
